### ISSUE TITLE
Propuesta de charla: Introducción a Laravel P2

### ISSUE THREAD

**Issue by jortiz3109** [medellin-php/meetup#1]
🎤 Quiero ser el próximo speaker

## Titulo de la charla

Introducción a Laravel: P2

## Breve descripción

La idea de la charla es iniciar un pequeño desarrollo usando el framework de desarrollo Laravel.

**Comment by eduarguz** [comment]
Tendrías disponible presentar esta charla el Jueves 05 de Diciembre de 2019? Horario 6.30 pm - 8.30 pm ?

**Comment by jortiz3109** [comment]
Si
