### ISSUE TITLE
[Propuesta Speaker] - Patrones de diseño - Adapter y Repository

### ISSUE THREAD

**Issue by darioriverat** [medellin-php/meetup#2]
🎤 Quiero ser el próximo speaker

## Titulo de la charla

Patrones de Diseño  - Adapter y Repository

## Breve descripción

La idea es seguir la línea del primer meetup y exponer otros dos patrones de diseño en PHP. Escogí adapter y repository porque son los que más he utilizado y creo que puedo explicarlos de manera fluída.

**Comment by eduarguz** [comment]
Tendrías disponible presentar esta charla el Jueves 05 de Diciembre de 2019? Horario 6.30 pm - 8.30 pm ?

**Comment by darioriverat** [comment]
Si.

**Comment by eduarguz** [comment]
@fermius 

Queda para el próximo Jueves 06 de Febrero del 2020 6:30 pm

Gracias!!

**Comment by darioriverat** [comment]
Vale.

**Comment by eduarguz** [comment]
https://twitter.com/MedellinPHP/status/1222977235587665921

**Comment by eduarguz** [comment]
Gracias por tu charla @fermius 
Muy buena charla, esperamos que sigas en contacto con la comunidad ✌🏻
