### ISSUE TITLE
Propuesta Speaker - Desplegando una aplicación laravel con kubernetes

### ISSUE THREAD

**Issue by apolo96** [medellin-php/meetup#3]
🎤 Quiero ser el próximo speaker

## Titulo de la charla

Desplegando una aplicación laravel con kubernetes

## Breve descripción

En esta charla, quiero hacer una demostración de como desplegar una aplicación laravel utilizando kubernetes. Tambien enseñar una breve introducción a kubernetes. 

Kubernetes o k8s es una plataforma de administración de cargas de trabajo y servicios basados en contenedores. Con k8s puedes implementar estrategias de deployments y escalar aplicaciones sin preocuparse por el tiempo de inactividad.

**Comment by eduarguz** [comment]
Hola Andres @apolo96 nos da mucho gusto que quieras hacer una presentación en el meetup.

Estamos preparando el próximo meetup para el 06-Febrero-2020 a las 6.30 pm (por confirmar), tendrías disponible y preparada la charla para ese día?

Saludos

**Comment by apolo96** [comment]
Hola @eduarguz, muchas gracias! 

Si tengo disponibilidad para ese día. 

Saludos, nos vemos en el meetup!

**Comment by eduarguz** [comment]
https://twitter.com/MedellinPHP/status/1222977235587665921

**Comment by eduarguz** [comment]
Gracias por tu charla @apolo96 
Muy buena charla esperamos que sigas en contacto con la comunidad✌🏻
