### ISSUE TITLE
[Propuesta Speaker] - Laravel Nova

### ISSUE THREAD

**Issue by joselfonseca** [medellin-php/meetup#5]
🎤 Quiero ser el próximo speaker

## Titulo de la charla

Laravel Nova para crear paneles de administración

## Breve descripción

Laravel Nova es un producto que nos permite crear de manera muy sencilla paneles de administración e incluso aplicaciones completas usando Laravel y Vue JS. Veremos que es, en que casos se puede usar y que ventajas y herramientas nos da utilizarlo. 

https://www.youtube.com/watch?v=P6OblkO_Mf4&list=PLWIk9Jo3Sp-Vu_qYOFUkwSMTjZMefbyiu

**Comment by eduarguz** [comment]
Hola @joselfonseca tendrías disponible tu charla para nuestro proximo meetup?
En esta ocación será 100% online, fecha tentativa (Jueves 2 de Abril 2020)

**Comment by joselfonseca** [comment]
Hola @eduarguz sip, pero me gustaría dar esta primero https://github.com/medellin-php/meetup/issues/6 si es posible. O si quieren la de nova pues hacemos la de Nova haha

**Comment by eduarguz** [comment]
Si claro, la que tú prefieras
Te aviso cuando quede el evento confirmado 👍🏻
