### ISSUE TITLE
[Propuesta Speaker] GraphQL

### ISSUE THREAD

**Issue by joselfonseca** [medellin-php/meetup#6]
🎤 Quiero ser el próximo speaker

## Titulo de la charla

GraphQL - Que es eso?

## Breve descripción

GraphQL como lenguaje de consulta, veremos otra forma de hacer APIs dandole mas poder al front y usando esta especificación creada por un equipo de Facebook para solucionar uno de sus problemas en el Feed API.

https://www.youtube.com/watch?v=JAiBv5cO_tw

**Comment by eduarguz** [comment]
Estamos listos! https://www.meetup.com/es/MedellinPHP/events/270281843/

Nos vemos ese día! Saludos!
