### ISSUE TITLE
[Propuesta Speaker] Multiple authentication en Laravel

### ISSUE THREAD

**Issue by JoanSernaLeiton** [medellin-php/meetup#7]
🎤 Quiero ser el próximo speaker

## Breve descripción

La autenticación múltiple es muy importante en una aplicación laravel empresarial de gran escala  donde prefiera usar diferentes tablas para autenticacion, como siempre prefiere la tabla de 'usuarios' para el registro de usuarios y la tabla de 'administradores' para el usuario administrador. Y de esta manera, cree una seguridad sólida para su sistema.

**Comment by eduarguz** [comment]
Hola Joan, 
Muchas gracias por mostrar tu interés en ser Speaker para la comunidad

El plan sería hacer la charla el próximo Jueves 30 de Abril a las 6:30 pm por zoom
Tendrias disponible tu charla para ese día?

Saludos

**Comment by JoanSernaLeiton** [comment]
Si claro, ese día me parece perfecto, la charla también ya está lista faltaría revisar algunas cositas

**Comment by eduarguz** [comment]
Estamos listos! https://www.meetup.com/es/MedellinPHP/events/270281843/

Joan te envie un correo para ultimar algunos detalles.
Nos vemos ese día! Saludos!

**Comment by eduarguz** [comment]
De nuevo, Gracias por compartir Joan 
Nos vemos en la próxima
